model_list:
  - model_name: Qwen/Qwen3-VL-8B-Instruct
    litellm_params:
      model: sagemaker/endpoint-qwen3-vl-8b-1024-2025-12-05-04-15-04
      drop_params: True
      aws_access_key_id:
      aws_secret_access_key:
      aws_region_name:
